In [2]:
import numpy as np

In [15]:
"""
Generate Random Number
NumPy offers the random module to work with random numbers.
"""
#Generate a random integer from 0 to 100:

from numpy import random

x = random.randint(100)

print(x)

"""
Generate Random Float
The random module's rand() method returns a random float between 0 and 1.
"""
#Generate a random float from 0 to 1:

from numpy import random

x = random.rand()

print(x)

"""
Generate Random Array
In NumPy we work with arrays, and you can use the two methods from the 
above examples to make random arrays.Integers The randint() method takes
a size parameter where you can specify the shape of an array.
"""

#Generate a 1-D array containing 5 random integers from 0 to 100:

from numpy import random

x=random.randint(100, size=(5))

print(x)

#Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100:

from numpy import random

x = random.randint(100, size=(3, 5))

print(x)

"""The rand() method also allows you to specify the shape of the array."""
#Generate a 1-D array containing 5 random floats:

from numpy import random

x = random.rand(5)

print(x)

#Generate a 2-D array with 3 rows, each row containing 5 random numbers:
x = random.rand(3, 5)

print(x)

"""
Generate Random Number From Array
The choice() method allows you to generate a random value based on 
an array of values. The choice() method takes an array as a parameter 
and randomly returns one of the values.
"""
#Return one of the values in an array:

from numpy import random

x = random.choice([3, 5, 7, 9])

print(x)

#Generate a 2-D array that consists of the values in the 
#array parameter (3, 5, 7, and 9):

x = random.choice([3, 5, 7, 9], size=(3, 5))

print(x)

43
0.24953942060399348
[35 23 58 54 64]
[[83 42 20 85 23]
 [41 32 77 67 54]
 [76 68 28 59 53]]
[0.46339429 0.61233372 0.24053992 0.18599858 0.07930502]
[[0.11104509 0.04058589 0.50381682 0.08549613 0.88825707]
 [0.49736256 0.56199832 0.44523481 0.80755724 0.63839369]
 [0.10017021 0.82785345 0.2665325  0.34919961 0.56341573]]
9
[[7 9 7 3 9]
 [5 9 7 9 9]
 [7 5 7 7 5]]


In [17]:
"""
Generate a 1-D array containing 100 values, where each value has to be 
3, 5, 7 or 9.

The probability for the value to be 3 is set to be 0.1

The probability for the value to be 5 is set to be 0.3

The probability for the value to be 7 is set to be 0.6

The probability for the value to be 9 is set to be 0
"""

x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(100))

print(x)

"""
The sum of all probability numbers should be 1.

Even if you run the example above 100 times, the value 9 will never occur.

You can return arrays of any shape and size by specifying the shape 
in the size parameter.
"""

#Same example as above, but return a 2-D array with 3 rows, each containing 5 values.

from numpy import random

x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(3, 5))

print(x)

[7 5 7 7 7 7 7 3 7 5 3 5 3 3 7 5 7 5 7 5 7 3 7 3 7 7 5 5 7 3 5 7 7 5 7 5 5
 7 7 7 7 7 5 7 7 7 7 7 5 5 3 7 5 7 7 7 5 5 5 3 7 7 7 7 7 7 5 5 5 7 7 7 7 5
 5 5 7 7 5 7 7 7 7 3 7 7 3 7 5 5 5 5 7 7 7 3 5 7 3 7]
[[7 7 5 7 7]
 [5 7 7 5 3]
 [7 5 7 7 7]]


In [22]:
#Randomly shuffle elements of following array:

#The shuffle() method makes changes to the original array.

from numpy import random
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

random.shuffle(arr)

print(arr)

#Generate a random permutation of elements of following array:
#The permutation() method returns a re-arranged array (and leaves
#the original array un-changed).

arr1 = np.array([1, 2, 3, 4, 5])

print("permutation",random.permutation(arr1))

print("original array",arr1)

[1 3 4 2 5]
permutation [1 4 5 2 3]
original array [1 2 3 4 5]


In [24]:
#Without ufunc, we can use Python's built-in zip() method:

x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = []

for i, j in zip(x, y):
  z.append(i + j)
print(z)

#NumPy has a ufunc for this, called add(x, y) that will produce 
#the same result.
#With ufunc, we can use the add() function:

import numpy as np

x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = np.add(x, y)

print(z)

[5, 7, 9, 11]
[ 5  7  9 11]


In [30]:
"""
How To Create Your Own ufunc
To create your own ufunc, you have to define a function, 
like you do with normal functions in Python, then you add it to 
your NumPy ufunc library with the frompyfunc() method.
The frompyfunc() method takes the following arguments:

function - the name of the function.
inputs - the number of input arguments (arrays).
outputs - the number of output arrays.
"""

import numpy as np

def myadd(x, y):
  return x+y

myadd = np.frompyfunc(myadd, 2, 1)

print(myadd([1, 2, 3, 4], [5, 6, 7, 8]))

"""
The function to convert (myadd in this case).
The number of input arguments the function takes (2 for myadd).
The number of output values the function returns (1 for myadd)
"""
#Check the type of a function to check if it is a ufunc or not.

#A ufunc should return <class 'numpy.ufunc'>.

print(type(np.add))

#If it is not a ufunc, it will return another type, like this 
#built-in NumPy function for joining two or more arrays:

print(type(np.concatenate))
#If the function is not recognized at all, it will return an error:

#To test if the function is a ufunc in an if statement, 
#use the numpy.ufunc value (or np.ufunc if you use np as an alias for numpy):

import numpy as np

if type(np.add) == np.ufunc:
  print('add is ufunc')
else:
  print('add is not ufunc')

[6 8 10 12]
<class 'numpy.ufunc'>
<class 'function'>
add is ufunc


In [40]:
"""
Addition
The add() function sums the content of two arrays, 
and return the results in a new array.
"""
arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.add(arr1, arr2)

print(newarr)

"""
The subtract() function subtracts the values from one array with the values from another array, 
and return the results in a new array.
"""
newarr = np.subtract(arr1, arr2)

print(newarr)

"""
The multiply() function multiplies the values from one array with the values from another array, 
and return the results in a new array.
"""
newarr = np.multiply(arr1, arr2)

print(newarr)

"""
The divide() function divides the values from one array with the values from another array, 
and return the results in a new array.
"""
newarr = np.divide(arr1, arr2)

print(newarr)

"""
The power() function rises the values from the first array to the power of the values of the second array, 
and return the results in a new array.
"""
newarr = np.power(arr1, arr2)

print(newarr)
#The example above will return [1000 3200000 729000000 6553600000000 2500 0] which is the result of 10*10*10,
#20*20*20*20*20, 30*30*30*30*30*30 etc.
#take second array as power

"""
Both the mod() and the remainder() functions return the remainder of the values in the first array corresponding to the values in the 
second array, and return the results in a new array.
"""
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.mod(arr1, arr2)

print(newarr)

"""
The example above will return [1 6 3 0 0 27] which is the remainders when you divide 10 with 3 (10%3), 20 with 
7 (20%7) 30 with 9 (30%9) etc.
"""

import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.remainder(arr1, arr2)

print(newarr)

"""
Quotient and Mod
The divmod() function return both the quotient and the mod. The return value is two arrays, the first array contains the 
quotient and second array contains the mod.
"""

newarr = np.divmod(arr1, arr2)

print(newarr)

"""
The example above will return:
(array([3, 2, 3, 5, 25, 1]), array([1, 6, 3, 0, 0, 27]))
The first array represents the quotients, (the integer value when you divide 10 with 3, 20 with 7, 30 with 9 etc.
The second array represents the remainders of the same divisions.
"""

"""
Absolute Values
Both the absolute() and the abs() functions do the same absolute operation element-wise but we should use absolute()
to avoid confusion with python's inbuilt math.abs()
"""
arr = np.array([-1, -2, 1, 2, 3, -4])

newarr = np.absolute(arr)

print(newarr)


[30 32 34 36 38 40]
[-10 -10 -10 -10 -10 -10]
[200 231 264 299 336 375]
[0.5        0.52380952 0.54545455 0.56521739 0.58333333 0.6       ]
[ 1661992960   602408795           0  1487897765  1090519040 -1144744561]
[ 1  6  3  0  0 27]
[ 1  6  3  0  0 27]
(array([ 3,  2,  3,  5, 25,  1]), array([ 1,  6,  3,  0,  0, 27]))
[1 2 1 2 3 4]


In [45]:
"""
Truncation
Remove the decimals, and return the float number closest to zero. 
Use the trunc() and fix() functions.
"""
arr = np.trunc([-3.1666, 3.6667])

print(arr)

arr = np.fix([-3.1666, 3.6667])

print(arr)

"""
Rounding
The around() function increments preceding digit or decimal by 1 if >=5 
else do nothing.
E.g. round off to 1 decimal point, 3.16666 is 3.2
"""
arr = np.around(3.1666, 2)

print(arr)

"""
Floor
The floor() function rounds off decimal to nearest lower integer.

E.g. floor of 3.166 is 3.
"""
arr = np.floor([-3.1666, 3.6667])

print(arr)

"""
Ceil
The ceil() function rounds off decimal to nearest upper integer.

E.g. ceil of 3.166 is 4.
"""
arr = np.ceil([-3.1666, 3.6667])

print(arr)

[-3.  3.]
[-3.  3.]
3.17
[-4.  3.]
[-3.  4.]


In [51]:
"""
Logs
NumPy provides functions to perform log at the base 2, e and 10.

We will also explore how we can take log for any base by creating a custom ufunc.

All of the log functions will place -inf or inf in the elements if the log can not be computed.
"""
#Log at Base 2
#Use the log2() function to perform log at the base 2.
arr = np.arange(1, 10)

print(np.log2(arr))

"""
Note: The arange(1, 10) function returns an array with integers starting from 1 (included) to 10 (not included).
"""

#Log at Base 10
#Use the log10() function to perform log at the base 10.
arr = np.arange(1, 10)

print(np.log10(arr))

#Natural Log, or Log at Base e
#Use the log() function to perform log at the base e.
arr = np.arange(1, 10)

print(np.log(arr))

"""
Log at Any Base
NumPy does not provide any function to take log at any base, so we can use the frompyfunc() function along with inbuilt function math.log() 
with two input parameters and one output parameter:
"""
from math import log
import numpy as np

nplog = np.frompyfunc(log, 2, 1)

print(nplog(100, 15))

[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]
[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]
1.7005483074552052


In [60]:
"""
Summations
What is the difference between summation and addition?

Addition is done between two arguments whereas summation happens over n elements.
"""
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2])

print(newarr)

#Perform summation in the following array over 1st axis:

import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2], axis=1)

print(newarr)

"""
Cummulative Sum
Cummulative sum means partially adding the elements in array.

E.g. The partial sum of [1, 2, 3, 4] would be [1, 1+2, 1+2+3, 1+2+3+4] = [1, 3, 6, 10].

Perfom partial sum with the cumsum() function.
"""
arr = np.array([1, 2, 3])

newarr = np.cumsum(arr)

print(newarr)

"""Products
To find the product of the elements in an array, use the prod() function.
"""
arr = np.array([1, 2, 3, 4])

x = np.prod(arr)

print(x)
#24 because 1*2*3*4 = 24

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

x = np.prod([arr1, arr2])

print(x)

#Perform summation in the following array over 1st axis:

import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

newarr = np.prod([arr1, arr2], axis=1)

print(newarr)

"""Cummulative Product
Cummulative product means taking the product partially.

E.g. The partial product of [1, 2, 3, 4] is [1, 1*2, 1*2*3, 1*2*3*4] = [1, 2, 6, 24]

Perfom partial sum with the cumprod() function."""

arr = np.array([5, 6, 7, 8])

newarr = np.cumprod(arr)

print(newarr)

"""
Differences
A discrete difference means subtracting two successive elements.

E.g. for [1, 2, 3, 4], the discrete difference would be [2-1, 3-2, 4-3] = [1, 1, 1]

To find the discrete difference, use the diff() function.
"""
arr = np.array([10, 15, 25, 5])

newarr = np.diff(arr)

print(newarr)

"""
Returns: [5 10 -20] because 15-10=5, 25-15=10, and 5-25=-20

We can perform this operation repeatedly by giving parameter n.

E.g. for [1, 2, 3, 4], the discrete difference with n = 2 would be 
[2-1, 3-2, 4-3] = [1, 1, 1] , then, since n=2, we will do it once more, 
with the new result: [1-1, 1-1] = [0, 0]
"""
arr = np.array([10, 15, 25, 5])

newarr = np.diff(arr, n=2)

print(newarr)

#Returns: [5 -30] because: 15-10=5, 25-15=10, and 5-25=-20 AND 10-5=5 and 
#-20-10=-30

12
[6 6]
[1 3 6]
24
40320
[  24 1680]
[   5   30  210 1680]
[  5  10 -20]
[  5 -30]


In [63]:
"""
Finding LCM (Lowest Common Multiple)
The Lowest Common Multiple is the smallest number that 
is a common multiple of two numbers.
"""
num1 = 4
num2 = 6

x = np.lcm(num1, num2)

print(x)
#Returns: 12 because that is the lowest common multiple of both numbers 
#(4*3=12 and 6*2=12).

"""
Finding LCM in Arrays
To find the Lowest Common Multiple of all values in an array, you can use the reduce() method.
The reduce() method will use the ufunc, in this case the lcm() function, on each element, and 
reduce the array by one dimension.
"""
arr = np.array([3, 6, 9])

x = np.lcm.reduce(arr)

print(x)

#Find the LCM of all values of an array where the array contains all integers 
#from 1 to 10:

import numpy as np

arr = np.arange(1, 11)

x = np.lcm.reduce(arr)

print(x)

12
18
2520


In [65]:
"""
Finding GCD (Greatest Common Denominator)
The GCD (Greatest Common Denominator), also known as HCF (Highest Common Factor) is the biggest number 
that is a common factor of both of the numbers.
"""
num1 = 6
num2 = 9

x = np.gcd(num1, num2)

print(x)
#Returns: 3 because that is the highest number both numbers 
#can be divided by (6/3=2 and 9/3=3).

#Find the GCD for all of the numbers in the following array:

import numpy as np

arr = np.array([20, 8, 32, 36, 16])

x = np.gcd.reduce(arr)

print(x)

3
4


In [67]:
"""
Trigonometric Functions
NumPy provides the ufuncs sin(), cos() and tan() 
that take values in radians and produce the corresponding sin, cos and tan values.
"""
import numpy as np

x = np.sin(np.pi/2)

print(x)

#Find sine values for all of the values in arr:

import numpy as np

arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])

x = np.sin(arr)

print(x)

1.0
[1.         0.8660254  0.70710678 0.58778525]


In [71]:
"""
Convert Degrees Into Radians
By default all of the trigonometric functions take radians as parameters but we can convert radians to degrees and vice versa as well in NumPy.

Note: radians values are pi/180 * degree_values.
"""

#Convert all of the values in following array arr to radians:

import numpy as np

arr = np.array([90, 180, 270, 360])

x = np.deg2rad(arr)

print(x)

#Convert all of the values in following array arr to degrees:

import numpy as np

arr = np.array([np.pi/2, np.pi, 1.5*np.pi, 2*np.pi])

x = np.rad2deg(arr)

print(x)

"""
Finding Angles
Finding angles from values of sine, cos, tan. E.g. sin, cos and tan inverse (arcsin, arccos, arctan).

NumPy provides ufuncs arcsin(), arccos() and arctan() that produce radian values for corresponding sin,
cos and tan values given.
"""
x = np.arcsin(1.0)

print(x)

#Find the angle for all of the sine values in the array

import numpy as np

arr = np.array([1, -1, 0.1])

x = np.arcsin(arr)

print(x)

"""
Hypotenues
Finding hypotenues using pythagoras theorem in NumPy.

NumPy provides the hypot() function that takes the base and perpendicular 
values and produces hypotenues based on pythagoras theorem.
"""
base = 3
perp = 4

x = np.hypot(base, perp)

print(x)

[1.57079633 3.14159265 4.71238898 6.28318531]
[ 90. 180. 270. 360.]
1.5707963267948966
[ 1.57079633 -1.57079633  0.10016742]
5.0


In [75]:
"""
Hyperbolic Functions
NumPy provides the ufuncs sinh(), cosh() and tanh() 
that take values in radians and produce the corresponding sinh, cosh and tanh 
values..
"""
#Find sinh value of PI/2:

import numpy as np

x = np.sinh(np.pi/2)

print(x)

#Find cosh values for all of the values in arr:

import numpy as np

arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])

x = np.cosh(arr)

print(x)

"""
Finding Angles
Finding angles from values of hyperbolic sine, cos, tan.
E.g. sinh, cosh and tanh inverse (arcsinh, arccosh, arctanh).

Numpy provides ufuncs arcsinh(), arccosh() and arctanh() that 
produce radian values for corresponding sinh, cosh and tanh values given.
"""

x = np.arcsinh(1.0)

print(x)

#Find the angle for all of the tanh values in array:

import numpy as np

arr = np.array([0.1, 0.2, 0.5])

x = np.arctanh(arr)

print(x)

2.3012989023072947
[2.50917848 1.60028686 1.32460909 1.20397209]
0.881373587019543
[0.10033535 0.20273255 0.54930614]


In [80]:
"""
What is a Set
A set in mathematics is a collection of unique elements.

Sets are used for operations involving frequent intersection, 
union and difference operations.
"""

"""
Create Sets in NumPy
We can use NumPy's unique() method to find unique elements from any array. 
E.g. create a set array, but remember that the set arrays should only be 
1-D arrays.
"""
#Convert following array with repeated elements to a set:

import numpy as np

arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])

x = np.unique(arr)

print(x)

"""
Finding Union
To find the unique values of two arrays, use the union1d() method.
"""
import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

newarr = np.union1d(arr1, arr2)

print(newarr)

"""
Finding Intersection
To find only the values that are present in both arrays, 
use the intersect1d() method.
"""
import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

newarr = np.intersect1d(arr1, arr2, assume_unique=True)

print(newarr)

#Note: the intersect1d() method takes an optional argument assume_unique, which if set to True can speed up computation. 
#It should always be set to True when dealing with sets.

"""
Finding Difference
To find only the values in the first set that is NOT present in the seconds set, 
use the setdiff1d() method.
"""
set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])

newarr = np.setdiff1d(set1, set2, assume_unique=True)

print(newarr)

"""
Finding Symmetric Difference
To find only the values that are NOT present in BOTH sets, 
use the setxor1d() method.
"""
#Find the symmetric difference of the set1 and set2:

import numpy as np

set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])

newarr = np.setxor1d(set1, set2, assume_unique=True)

print(newarr)

[1 2 3 4 5 6 7]
[1 2 3 4 5 6]
[3 4]
[1 2]
[1 2 5 6]
